version: "3.8"
services:
  database:
    image: postgres:17-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dulcedeleche
      POSTGRES_DB: notes_db
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
